Add a check for explicit full export flag
Financial-Times/content-exporter pull request #30
Opened 2021-06-04 11:37 UTC by AlexKondov

# Description

## What

Add a check making sure that either a list of ids are passed or a full export is explicitly wanted.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-2237

## Anything, in particular, you'd like to highlight to reviewers

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-06-07 11:52 UTC, Zarrie reviewed
Looks really good to me, though I see there have not been tests for the code, which is not good, so maybe we should start introducing some? 
Please consider adding several tests for the newly added functionality.

2021-06-07 13:56 UTC, gotha approved these changes

2021-06-07 13:57 UTC, gotha requested changes
Can you please update the README file with information about how full export can be triggered

2021-06-07 15:37 UTC, atanasdinov commented on queue/kafka.go
> +	"errors"
I love seeing you have re-formatted the imports. Could you perhaps change this import to `fmt` instead while at it?

2021-06-07 15:37 UTC, atanasdinov commented on web/resources.go
> +	if len(candidates) == 0 && !isFullExport {
It will probably take a little bit of time to add proper tests however I think we'd greatly benefit from those. What's your opinion?

2021-06-07 15:37 UTC, atanasdinov commented on web/resources.go
>  func getCandidateUUIDs(request *http.Request) (candidates []string) {
From my understanding of the ticket description, we'd like to use `{ "uuids" : ""}`  as a valid payload which means we'd probably want to update this function as well.

2021-06-08 13:16 UTC, atanasdinov submitted a review, later dismissed
LGTM!

2021-06-09 08:38 UTC, Zarrie approved these changes
Well done 🚀

2021-06-09 08:48 UTC, atanasdinov approved these changes

2021-06-09 12:35 UTC, gotha approved these changes

2021-06-10 07:04 UTC, merged