Remove full exports deployment
Financial-Times/content-exporter pull request #37
Opened 2022-04-14 14:57 UTC by atanasdinov

# Description

## What

Removes obsolete deployment.

## Why

[JIRA Ticket](https://financialtimes.atlassian.net/browse/UPPSF-3038)

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-04-14 15:17 UTC, dtvalk-ov approved these changes

2022-04-14 15:20 UTC, dtvalk-ov requested changes
There is a line about full exporter deployment in the Readme that needs to be removed as well

2022-04-15 06:21 UTC, dtvalk-ov approved these changes

2022-04-15 08:40 UTC, martin-stanchev approved these changes

2022-04-19 11:19 UTC, merged