Handle case for running full export and failing healthcheck with kafka lag
Financial-Times/content-exporter pull request #39
Opened 2022-07-12 10:41 UTC by dtvalk-ov

@Financial-Times/content-team as the test full export is still running on Dev (it's expected to finish today after 6PM), I still haven't verified that the Job successfully changes its status to TERMINATED and then the healthcheck will be back to normal, but I'm opening the PR so you can take a look. I will confirm it tomorrow morning and proceed accordingly 

**Update**: When the full export task finished, the job changes it status as expected. The lag after the job termination was above 10k, but the service could catch-up quickly and the healthcheck was back to normal

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3351

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-07-12 13:46 UTC, ilian2233 approved these changes

2022-07-13 07:48 UTC, martin-stanchev approved these changes

2022-07-13 08:01 UTC, atanasdinov requested changes
The approach is great! Just need to make sure this is properly tested with relation to the comments.

2022-07-13 08:01 UTC, atanasdinov commented on healthcheck.go
> +	msg := fmt.Sprintf("%s: %s", fullExportMessage, err.Error())
If a full export is running but there's no lag, wouldn't this panic with `nil pointer dereference`?

2022-07-13 08:03 UTC, dtvalk-ov commented on healthcheck.go
> +	msg := fmt.Sprintf("%s: %s", fullExportMessage, err.Error())
There is a nil check above, so when no lag error is returned the message won't be shown

2022-07-13 08:17 UTC, atanasdinov approved these changes

2022-07-13 08:18 UTC, martin-stanchev approved these changes

2022-07-14 06:40 UTC, merged